    #FROM ubuntu:latest
    FROM docker:openjdk
    MAINTAINER vlad
    RUN apt-get update -qq

    #Logstash
    RUN wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
    RUN apt-get install -q apt-transport-https
    RUN "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | tee -a /etc/apt/sources.list.d/elastic-5.x.list
    RUN apt-get update -q
    RUN apt-get install -q logstash
